import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Trash2, ArrowRight, Edit } from "lucide-react";
import { formatDate } from "../lib/utils";
export function PostCard({ post, onDelete }) {
    const truncatedDescription = post.content.length > 100 ? post.content.substring(0, 100) + "..." : post.content;
    return (_jsxs(Card, { className: "overflow-hidden hover:shadow-lg transition-shadow duration-300 flex flex-col h-full", children: [_jsx("div", { className: "relative w-full h-48 bg-gray-100 overflow-hidden", children: _jsx("img", { src: post.thumbnail || "/placeholder.svg", alt: post.title, className: "w-full h-full object-cover hover:scale-105 transition-transform duration-300" }) }), _jsxs(CardContent, { className: "pt-4 flex-grow", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900 mb-2 line-clamp-2", children: post.title }), _jsxs("div", { className: "space-y-1 mb-3 text-sm text-gray-500", children: [_jsxs("p", { children: [_jsx("span", { className: "font-medium", children: "T\u00E1c gi\u1EA3:" }), " ", post.author] }), _jsxs("p", { children: [_jsx("span", { className: "font-medium", children: "Ng\u00E0y \u0111\u0103ng:" }), " ", formatDate(post.date)] })] }), _jsx("p", { className: "text-sm text-gray-600 line-clamp-3", children: truncatedDescription })] }), _jsxs(CardFooter, { className: "gap-2 pt-4", children: [_jsx(Link, { to: `/posts/${post.id}`, className: "flex-1", children: _jsxs(Button, { variant: "default", className: "w-full gap-2", children: ["\u0110\u1ECDc th\u00EAm", _jsx(ArrowRight, { className: "w-4 h-4" })] }) }), _jsx(Link, { to: `/posts/edit/${post.id}`, children: _jsx(Button, { variant: "outline", size: "icon", title: "Ch\u1EC9nh s\u1EEDa b\u00E0i vi\u1EBFt", children: _jsx(Edit, { className: "w-4 h-4" }) }) }), _jsx(Button, { variant: "destructive", size: "icon", onClick: onDelete, title: "X\u00F3a b\u00E0i vi\u1EBFt", children: _jsx(Trash2, { className: "w-4 h-4" }) })] })] }));
}
